### PR TITLE
resolves #16 emit error from stream created by no-args src function

### LINKED ISSUE #16: src function does not emit error to stream when input is a buffer
When the src function is called without arguments to accept buffer objects in the stream, the error event is not emitted back to that stream. As a result, there's no way to catch an error reading the contents of the zip.

For example:

```js
vfs.src('no-a-zip-file.txt')
  .pipe(gvzip.src())
  .on('error', (err) => console.log('error reading zip: ' + err.message))
  .pipe(gvzip.dest('out.zip'))
```

The error callback is never invoked. Instead, we see:

```
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: end of central directory record signature not found
    at /project/node_modules/yauzl/index.js:187:14
    at /project/node_modules/yauzl/index.js:631:5
```

The reason has to do with the fact that es.merge does not automatically propagate the error event. Therefore, it must be done explicitly.

I'll submit a PR.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@joaomoreno Please let me know if there's anything I can do to help get this merged and released. It's currently preventing me from handling errors in my application. Thanks!

**Comment by mojavelinux** [comment]
This seems like a slightly simpler implementation:

```js
function unzip() {
    return through2.obj(function (file, enc, next) {
        if (!file.isBuffer()) return next(new Error('Only supports buffers'));
        yauzl.fromBuffer(file.contents, (err, zip) => {
            if (err) {
                // NOTE if we use next(err), the pipe to dest is still called
                this.emit('error', err)
            } else {
                toStream(zip)
                    .on('data', (data) => this.push(data))
                    .on('error', next)
                    .on('end', next)
            }
        });     
    });
}
```

It also handles errors during unzip.

**Comment by joaomoreno** [comment]
If you'd like feel free to rewrite it with that version.

**Comment by mojavelinux** [comment]
Thanks for getting back to me @joaomoreno! I've gone ahead and updated the implementation.

**Comment by mojavelinux** [comment]
What I can't figure out is why this works:

```
this.emit('error', err)
```

But this doesn't:

```
next(err)
```

If I call next(err), then dest will create an empty zip. That's because the complete callback on dest is still invoked. But if I emit the error, it won't be.

As far as I can tell, the code as proposed is working correctly. If an error occurs, and pipe to dest is the next in the chain, the zip file will not be created.

**Comment by mojavelinux** [comment]
For what it's worth, gulp-gunzip does the same thing. It seems like `this.emit('error', err)` is required when called from an async callback. I'm more confident now this is the right approach.

**Comment by joaomoreno** [comment]
Thanks!

**Comment by mojavelinux** [comment]
Thanks @joaomoreno!

**Comment by mojavelinux** [comment]
@joaomoreno I realized the style of the code for unzipFile and unzip now different. For consistency, should I submit a PR to write unzip in the same way? In other words:

```js
yauzl.fromBuffer(file.contents, (err, zip) => {
    if (err) return this.emit('error', err);
    toStream(zip)
        .on('error', next)
        .on('data', (data) => this.push(data))
        .on('end', next)
});
```

Perhaps we should set up standard JS on the project so that the code formatting stays consistent? I could help with that too.

**Comment by joaomoreno** [comment]
Sure, feel free to submit PR!

**Comment by mojavelinux** [comment]
@joaomoreno Awesome! Comin' your way!

**Pull request merged**
