### PR TITLE
resolves #26 fix file mode calculation error caused by missing constants

### LINKED ISSUE #26: modeFromEntry returns incorrect mode value on Windows
It turns out that not all `fs.constants` are set on Node for Windows (or the constants are platform dependent). Thus, when we switched from hard coded values to using fs.constants, the computation in modeFromEntry broken on Windows. As a result, it returns a rather arbitrary value.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Since this is a bug fix, I think it should be released with 2.2.1.

**Comment by mojavelinux** [comment]
@joaomoreno Can I merge?

**Comment by mojavelinux** [comment]
@joaomoreno I hate to be bother about this, but this bug is preventing users of my application on Windows from being able to delete files extracted by this library. Could you review / approve as soon as you get a chance? Thanks in advance!

**Comment by mojavelinux** [comment]
@joaomoreno If you don't have time to look at this right now, please at least let me know so I can make other arrangements. I need to determine whether I need to make a new release of my application with a fix or whether users will be able to pull down a patch release of gulp-vinyl-zip.

**Comment by joaomoreno** [comment]
Sorry @mojavelinux didn't check notifications since Thursday. This looks OK to me.

**Comment by mojavelinux** [comment]
Thank you so much! I really appreciate it.

Would you have time to publish a 2.2.1 release?

**Comment by joaomoreno** [comment]
Published v2.4.0

**Comment by mojavelinux** [comment]
Can you publish it as 2.2.1 instead? There are two reasons for this:

1. It's a bugfix, so it should be available as a patch release, not a minor release
2. My application is locked at 2.2, so users won't get the update to 2.4 unless I release a whole new version.

Please consider releasing this fix in a 2.2.1 release.

p.s. I'm also not sure why you skipped 2.3. But that's another matter.

**Comment by joaomoreno** [comment]
Somehow npm didn't let me publish 2.3.0.

I also fixed security vulnerabilities so all of that got bundled together in 2.4.0.

I can do a 2.2.1 for you.

**Comment by mojavelinux** [comment]
Thanks!!!

**Comment by joaomoreno** [comment]
Done

**Comment by mojavelinux** [comment]
Thank you for doing that. I really appreciate it. (You saved my :peach:).

**Pull request merged**
