### PR TITLE
resolves #21 configure standard JS linter on project

### LINKED ISSUE #21: Configure linter on project
Configure the [standard JS](https://standardjs.com/) linter on the project to ensure the code is consistently styled.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@joaomoreno this is finally working on Node 6. We had to downgrade standard JS to 12 to get support. Hardly any updated library supports Node 4 anymore, so there's no reasonable way to get that working.

My other PR will add 8, 10, and 12 once this is merged in.

**Comment by mojavelinux** [comment]
To see the non-whitespace changes, refer to https://github.com/joaomoreno/gulp-vinyl-zip/pull/22/files?w=1

**Comment by mojavelinux** [comment]
@joaomoreno wdyt? Are you ready to take the plunge into standard JS or would you like to request changes?

**Comment by joaomoreno** [comment]
Sorry, been busy! Let's do it.

**Comment by joaomoreno** [comment]
Btw, would you like to become a contributor? I can give you commit rights.

**Comment by mojavelinux** [comment]
Sure. I'm using gulp-vinyl-zip in Antora, so it will be a part of my software for the foreseeable future. So it's in my best interest to make sure it receives :heart:.

**Comment by joaomoreno** [comment]
Done! :+1: 

Thanks for all the effort. I'll still keep npm rights, so let me know when you want me to publish new versions.

**Comment by mojavelinux** [comment]
Sound good!

**Pull request merged**
