### PR TITLE
resolves #15 remove dependency on event-stream

### LINKED ISSUE #15: Find alternative to event-stream now that it's archived
Due to "the incident", event-stream is now archived. Can we just move away from it entirely? How much does gulp-vinyl-zip rely on it? Is there an alternative? Perhaps take a page from this PR? https://github.com/sweetalert2/sweetalert2/pull/1305/files

### PR DESCRIPTION
**Pull request by mojavelinux**
Use the through library directly.

### CODE REVIEW

**Review by joaomoreno — APPROVED** [review]

**Comment by mojavelinux** [comment]
I think this change warrants a release. wdyt?

**Comment by joaomoreno** [comment]
Published 2.2.0!

**Comment by mojavelinux** [comment]
Thanks!

**Comment by mojavelinux** [comment]
@joaomoreno FYI the 2.2.0 release didn't get a tag.

**Comment by joaomoreno** [comment]
@mojavelinux Thanks for the ping, pushed the tag.

**Pull request merged**
